# Generated by Django 5.0.7 on 2024-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('extrait', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('acticle', models.TextField()),
                ('image', models.FileField(upload_to='actualité')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('cubage', models.CharField(max_length=20)),
                ('duree', models.CharField(max_length=20)),
                ('lieu', models.CharField(max_length=20)),
                ('type_d', models.CharField(max_length=20)),
                ('details', models.TextField()),
            ],
        ),
    ]
